spring:
  profiles:
    #激活开发环境
    active: xia
  messages:
    basename: i18n/Messages,i18n/Pages
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://172.16.2.67:3306/coverage?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
logging:
  config: classpath:log4j2.yml
swagger:
  base-package: com.digiwin.code.coverage.backend.controller
  authorization:
    type: None
server:
  port: 8888
  servlet:
    session:
      timeout: 3600
